## Numpy


numpy.org

In [2]:
import numpy as dsa    #aqui o prof deu esse apelido para a biblioteca

In [3]:
dsa.__version__

'1.23.5'

In [4]:
# Para instalar versao exata do pacote em Python
# !pip install numpy==1.22.2

### Criando Arrays NumPy

In [5]:
# Array criado a partir de lista
arr1 = dsa.array([10,21,32,43,48,15,76,57,89])

In [6]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [7]:
type(arr1)

numpy.ndarray

In [8]:
#formato do array
arr1.shape

(9,)

In [10]:
#shape(eixo0_qtd_elementos,eixo1_qtd_elementos)  ->> shape(9,) ->> array de 1 dimensão apenas = vetor

### Indexação em Arrays NumPy

In [11]:
arr1[4] # elemento no indice 4

48

In [13]:
# Indexação - posição 1 até posição 4, exclusive!
arr1[1:4]

array([21, 32, 43])

In [14]:
arr1[1:4+1]

array([21, 32, 43, 48])

In [15]:
# Cria lista de indices
indices = [1, 2, 5, 6]

In [16]:
arr1[indices]  #mostra os valores nas posições dos indices passados no parametro

array([21, 32, 15, 76])

In [19]:
# Máscara booleana para elementos pares (divide cada ELEMENTO do array por 2, resto div = 0)
mask = (arr1 % 2 == 0)

In [20]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [18]:
arr1[mask]   #retorna onde o array tiver indice True apenas

array([10, 32, 48, 76])

In [21]:
arr1[0] = 100 #substituir valor

In [22]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [23]:
#Não é possível incluir elemento de outro tipo
try:
    arr1[0] = 'Novo elemento'
except:
    print("Operação não permitida!")

Operação não permitida!


### Funções NumPy

In [24]:
# np.array cria um array Numpy
arr2 = dsa.array([1, 2, 3, 4, 5])

In [25]:
print(arr2)

[1 2 3 4 5]


In [26]:
type(arr2)

numpy.ndarray

In [29]:
# Digite. e pressione a telca tab para visualizar os m´todos do NumPy
#arr2.

In [31]:
# Soma acumulada dos elementos do array
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [32]:
# Produto acumulado dos elementos do array
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [33]:
# arange - cria array NumPy contendo uma progressão aritimética a partir de um intervalo - (start, stop, step) , stop é EXCLUSIVO.
arr3 = dsa.arange(0, 50, 5)

In [34]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [35]:
type(arr3)

numpy.ndarray

In [36]:
dsa.shape(arr3)

(10,)

In [37]:
print(arr3.dtype)  # tipos de dados DENTRO do array

int64


In [38]:
# Array preenchido com zeros
arr4 = dsa.zeros(10)

In [39]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
